name: (Pylint + Flake8) linters + Black formatter

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint
      - uses: actions/checkout@v3
      - name: Running black formatter
        uses: psf/black@stable
      - name: Linting with pylint
        run: pylint $(git ls-files '*.py')
      - name: Linting with flake8
        uses: TrueBrain/actions-flake8@v2
        with:
          plugins: "flake8-bugbear==22.1.11 flake8-black"
