name: (Pylint + Flake8) linters + Black formatter

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint
      - name: Running black formatter
        uses: actions/checkout@v2
      - uses: psf/black@stable
      - name: Linting with pylint
        run: find . -name '*.py' -exec pylint {} \;
      - name: Linting with flake8
        uses: py-actions/flake8@v2
